
[font]
normal.family = "EnvyCodeR Nerd Font"
bold.family = "EnvyCodeR Nerd Font"
italic.family = "EnvyCodeR Nerd Font"
bold_italic.family = "EnvyCodeR Nerd Font"
size = 11

[[hints.enabled]]
hyperlinks = true
post_processing = true
regex = "(https:|http:)\\S+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.command]
program = "chromium-browser"
args = ["--incognito"]

[hints.enabled.mouse]
enabled = true
mods = "None"

[general]
import = [
    "~/.config/alacritty/themes/default.toml"
]
